builds:
- main: ./cmd/main.go
  binary: helmvcs
  env:
  - CGO_ENABLED=0
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64

archive:
  files:
  - CHANGELOG.md
  - LICENSE
  - README.md
  - plugin.yaml
