name: "vcs"
version: "0.1.0"
usage: "A Helm plugin that turns any version control system (bzr, git, hg, svn) into a chart repository"
description: |-
  Allows Helm to directly use any existing VCS as a chart repository, without changes. Supports Bazaar, Git, Mercurial and Subversion.
  https://github.com/steven-sheehy/helm-vcs
command: "$HELM_PLUGIN_DIR/helmvcs"
downloaders:
- command: "helmvcs"
  protocols:
  - "bzr"
  - "git"
  - "hg"
  - "svn"
