version: 2

workflows:
  version: 2
  test-build-deploy:
    jobs:
    - test

jobs:
  test:
    docker:
    - image: circleci/golang:1.11
    working_directory: /usr/src/helm-vcs
    steps:
    - checkout
    - restore_cache:
      keys:
        - go-mode-{{ checksum "go.sum" }}
    - run
      name: "Run unit tests"
      command: "make test"
    - save_cache:
      key: go-mod-{{ checksum "go.sum" }}
      paths:
      - "/go/pkg/mod"
