version: 2

workflows:
  version: 2
  main:
    jobs:
    - build
    - lint
    - test
    - release:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /.*/
        requires:
        - build
        - lint
        - test

defaults: &defaults
  docker:
  - image: circleci/golang:1.12

cache: &cache
  keys:
  - go-mod

jobs:
  build:
    <<: *defaults
    steps:
    - checkout
    - restore_cache: *cache
    - run: make build
    - save_cache:
        key: go-mod
        paths:
        - "/go/pkg/mod"
  lint:
    <<: *defaults
    steps:
    - checkout
    - run: make lint
  test:
    <<: *defaults
    steps:
    - checkout
    - restore_cache: *cache
    - run: make test
  release:
    <<: *defaults
    steps:
    - checkout
    - restore_cache: *cache
    - run: curl -sL https://git.io/goreleaser | bash
